#! confirguration/base.yaml
application: 
  port: 8000
database:
  host: localhost
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
#! confirguration/local.yaml
application:
  host: 127.0.0.1
#! configuration /production.yaml
application:
  host: 0.0.0.0
